### ISSUE TITLE
Layout breaks when changing from landscape to portrait mode: voice bar disappears

### ISSUE THREAD

**Issue by r03ert0** [ConnectProject/mavoix-app#40]
Changing from landscape to portrait mode breaks the layout. Changing back from portrait to landscape mode breaks it even more, making the voice bar disappear (see image). Also, images change aspect ratio: they are originally squared, now they are rectangular. The problem is the same when starting in portrait mode and changing to landscape.

![IMG_4423](https://user-images.githubusercontent.com/2310732/106393969-52611500-63fa-11eb-9738-f524a7fc8b75.png)

**Comment by ntraut** [comment]
I think that issue was fixed on a3999a88ed1c5606105d689d692e78488266836f because `orientationchange` event does not do anything since this commit (I tested on an ipad and didn't see this problem) (some code cleaning may left to be done but this should not affect app behavior).

**Comment by r03ert0** [comment]
I just installed Release 5 for iOS from AppCenter, and the bug is still there...

**Comment by ntraut** [comment]
Release 5 is built on the merge from debug-romain branch, commit a3999a88ed1c5606105d689d692e78488266836f came after. There are more recent releases (6 and 7), could you try them?

**Comment by r03ert0** [comment]
Oh! I'll check that.
In my interface they are all called the same: Version 1.0 (1), starting in January 4, and until February 8. Is it possible to change the version to something like 1.0.1, 1.0.2, etc.?
It would be also good maybe to display the version with a small font in a corner of the interface, so that when people report a bug they can tell which version they were using.

**Comment by r03ert0** [comment]
Nice! the layout bug seems to be fixed! 🥳 
however, now there's a new bug: image names go outside from the picture. I will close this issue and open a new one.
